### ISSUE TITLE
explore_outliers() function feedback

### ISSUE THREAD

**Issue by pokrovskyy** [UBC-MDS/xplrrr#34]
[AndresPitta](https://github.com/AndresPitta)
- [x] The documentation could be more informative regarding the technique used to select outliers. Reading the code, I see it is using 2 standard deviations, but the documentation could be clearer.

- [x] The function does not work unless the whole dataset is numeric. I consider the function could just generate the outliers for the numeric variables and ignore the character variables.

- [ ] This function could adopt the explore_missing parameter type, to generate count and location.

[Keanna-K](https://github.com/Keanna-K)
- [x] It would be nice if it was explicitly stated how the outliers are being defined (i.e. 1.5x the IQR), this reinforces a sense of trust. when using someone else's package. 

- [x] Additionally, it would be nice if all the package functions were consistent in how they deal with non-numeric data frames/columns. Specifically, this function requires the entire data frame to be numeric whereas the explore_feature_map simply excludes the non-numeric columns.

**Comment by fkhan72** [comment]
included the checked points in the updated version of explore_outliers function
